version: '4.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - proxy-network

  backend1:
    build: ./backend1
    ports:
      - "4000:4000"
    networks:
      - proxy-network

  backend2:
    build: ./backend2
    ports:
      - "5000:5000"
    networks:
      - proxy-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend1
      - backend2
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
